[workspace]
resolver = "2"
members = [
	"libgsh",
	"client",
	"examples/colors",
	"examples/cube",
	"examples/password_auth",
	"examples/signature_auth",
	"examples/remote_desktop",
	"examples/quic_demo",
]
