[package]
name = "libgsh"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
rcgen = "0.13.2"
log = "0.4.27"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
tokio-rustls = { version = "0.26.2", features = ["ring"] }
async-trait = "0.1.88"
