[package]
name = "libgsh"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
rustls = { version = "0.23.26", features = [
    "ring",
    "std",
], default-features = false }
rcgen = "0.13.2"
log = "0.4.27"
