[package]
name = "remote_desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
libgsh = { workspace = true }
log = "0.4.27"
env_logger = "0.11.8"
xcap = { version = "0.5.1", features = ["image"] }
