name: Release

# Needed so the release job can publish assets
permissions:
  contents: write     # allows creating & uploading releases

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    name: Build (${{ matrix.os }} • ${{ matrix.target }})
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest , target: x86_64-unknown-linux-gnu , exe: ""     }
          - { os: windows-latest, target: x86_64-pc-windows-msvc   , exe: ".exe" }
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Install deps (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - uses: actions/upload-artifact@v4
      with:
        name: gsh-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/gsh${{ matrix.exe }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions: { contents: write }

    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: gsh-*        # grab every artifact we just built
        path: dist            # put them in one folder
        merge-multiple: true

    - uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false
        files: dist/*
