name: Client Release

# Needed so the release job can publish assets
permissions:
  contents: write     # allows creating & uploading releases

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Client (${{ matrix.os }} • ${{ matrix.target }})
    strategy:
      matrix:
        include:
          - { suffix: _x64_linux,   os: ubuntu-latest , target: x86_64-unknown-linux-gnu , exe: ""     }
          - { suffix: _x64_win, os: windows-latest, target: x86_64-pc-windows-msvc   , exe: ".exe" }
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    # ----------------------------------
    # Install protoc everywhere (one step, cross-platform)
    # ----------------------------------
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Client
      run: cargo build -p gsh --release --target ${{ matrix.target }}

    - name: Copy binary with suffix
      run: |
        cp "target/${{ matrix.target }}/release/gsh${{ matrix.exe }}" "gsh_${{ matrix.suffix }}${{ matrix.exe }}"

    - uses: actions/upload-artifact@v4
      with:
        name: gsh-${{ matrix.suffix }}
        path: gsh_${{ matrix.suffix }}${{ matrix.exe }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions: { contents: write }

    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: gsh-*        # grab every artifact we just built
        path: dist            # put them in one folder
        merge-multiple: true

    - uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false
        files: dist/*
